site_name: "Vinti4Net PHP SDK"
site_description: "Documentação oficial do SDK Vinti4Net PHP"
site_author: "Eril TS Carvalho"

nav:
  - Home: index.md
  - Instalação: installation.md
  - Compra: 'compra.md'
  - Serviço: 'pagamento-servico.md'
  - Recarga: 'recarga.md'
  - Callback: 'callback.md'
  - Classes:
      - PaymentClient: classes/payment-client.md
      - PaymentRequest: classes/payment-request.md
      - PaymentResult: classes/payment-result.md